version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuserpass
      POSTGRES_DB: testdb
    ports:
     - 3306:3306
  worth:
    depends_on:
      - db
    image: wortheum/worth
    build: .
    environment:
      DATABASE_URL: postgresql://testuser:testuserpass@db:5432/testdb
      LOG_LEVEL: INFO
      WORTHS_URL: https://api.wortheum.news
    links:
      - db:db
    ports:
      - 8080:8080
    volumes:
      - .:/app
    restart: always
